# Generated by Django 4.2.5 on 2023-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('excerpt', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
